FROM node:26.5.0-alpine3.24 AS builder

WORKDIR /app

RUN npm install -g pnpm@11.15.0

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/docs/package.json apps/docs/package.json

RUN pnpm install --frozen-lockfile

COPY apps/docs ./apps/docs

RUN pnpm build:docs


FROM nginx:stable-alpine3.23-slim

COPY nginx.docs.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/docs/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]